### ISSUE TITLE
Hugslib + Deep Storage results in unplayable game state

### ISSUE THREAD

**Issue by Drexl** [lilwhitemouse/RimWorld-LWM.DeepStorage#144]
Mod List:
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core
Royalty
Ideology
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
LWM's Deep Storage [https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896]

Issue:
With HugsLib and Deep Storage installed the following issues occur:

- Inability to interract with any game objects or pan the map. 
- Immediately after crash-landing the game keeps spawning steel slag chunks until they reach the end of the map.
- Mod options page is blank.

Log: [log.txt](https://github.com/lilwhitemouse/RimWorld-LWM.DeepStorage/files/11319299/log.txt)
![image](https://user-images.githubusercontent.com/2714403/234190909-d52973a1-d057-48e3-b419-0b6bb299026b.png)

**Comment by LamkasDev** [comment]
+1

**Comment by lilwhitemouse** [comment]
Some mod or another has failed. Your best bet is to force Steam to redownload or check the integrity of the mod and if that doesn't help....do that for all other mods.

It's a weird thing, and I have yet to figure out how to cause it deliberately, but resetting the downloaded mods usually helps!

**Comment by Drexl** [comment]
@Xetaxheb that was incredibly helpful. Thank you!

**Comment by lilwhitemouse** [comment]
Dear archotechy gods! That's a subtle thing that <s>could very well be</s> is almost certainly causing the problem!
I removed the LoadFolders at some point because it was a real pain to keep up to date, and because with 1.4 it was no longer useful, and if it's still around, it could f--- things up. You might bring this up with the rimpy people!
I will look into whether an empty LoadFolders file causes problems, and can put one back if that would help.
