### ISSUE TITLE
Weird cut-off of the Deep freezer inspector panels

### ISSUE THREAD

**Issue by ZzZombo** [lilwhitemouse/RimWorld-LWM.DeepStorage#68]
https://cdn.discordapp.com/attachments/667587631965667328/702748198720110603/unknown.png.

For some reason the top part of the panels are cut off, leaving me w/o any way to change storage settings, for example.

**Comment by lilwhitemouse** [comment]
I'm afraid I cannot control if anyone changes the size of the inspect window and pushes the ITabs off the top of the screen...

I have wondered in the past what happens if someone has a smaller screen.  I can promise that if/when I add "Anyone may take" checkboxes for Restricted Storage to the Storage and Contents tabs, it will be controllable via a mod setting.

I suggest removing whichever mod shows the contents in the inspect window thing (where it says "Ambrosia x 3 frigita crystals x 10 ...")  Also, you can open and close the ITabs by pressing on them again, if that helps?

If I'm missing something I should be doing, feel free to reopen this, and point it out to me again :)

**Comment by ZzZombo** [comment]
Sadly the screenshot doesn't show this (and I can't take another because I'd have first to salvage a mod incompatibility that have cropped up just yesterday first), but the tabs exhibit empty space at the bottom that seemingly comes out of nowhere. I believe it's in your capacity to get rid of it and then you might be able to reduce the required height of the panels just enough so it's no longer an issue.

**Comment by lilwhitemouse** [comment]
Can you reproduce the space in any other screenshot?

**Comment by ZzZombo** [comment]
https://cdn.discordapp.com/attachments/667587631965667328/702748198720110603/unknown.png
https://cdn.discordapp.com/attachments/667587631965667328/704122518922854490/unknown.png

**Comment by lilwhitemouse** [comment]
So what am I looking at?  In the first picture, you can't actually change storage priority or anything, yes?  I don't have any idea what I might be able to change there...

I'm LWM#7117 on discord, by the way, if that's a preferred channel for you.

**Comment by ZzZombo** [comment]
Don't you see the dreaded empty space on both pictures? Eliminate that, and then you can shrink the height of the panels just enough to fit into the screen nicely. On the first picture you can even see that despite having a single stack of items, the tab still wants to go off-screen. And on the latter, even though it still fits into the screen with all those entries taking up nearly a few pages of entries, some empty space pushes them up. Also, Discord friend request sent!
