### ISSUE TITLE
Right click disabled in v.1.1.2559

### ISSUE THREAD

**Issue by naztharune** [lilwhitemouse/RimWorld-LWM.DeepStorage#86]
Hey, I feel like you should probably know that in RimWorld v.1.1.2559 with this mod installed I can't seem to right click on objects to get my colonists to perform actions such as equip weapons in-game. The only other mods installed were HugsLib and Harmony. This was ultimately resolved by updating the game to v.1.1.2654, making this issue relatively small as presumably most people would have updated by now; however, I feel like it's still worth mentioning just in case it is useful somewhere down the line. Thanks!

**Comment by lilwhitemouse** [comment]
OMG, that can explain so much! I have gotten a lot of complaints from people about that, and I was always confused. It *very* possible I never saw version 2559, because I often keep RW open for well over a week at a time, so it can't update. I may have completely skipped the 2559 version and never seen the problem!

Thanks!
